// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA9VLC5pwOT-qa5Bnbtzt-GddH_kYWHRa4',
    appId: '1:1059902399419:web:119c4228e55aeab5031a9e',
    messagingSenderId: '1059902399419',
    projectId: 'dishh-c672c',
    authDomain: 'dishh-c672c.firebaseapp.com',
    storageBucket: 'dishh-c672c.appspot.com',
    measurementId: 'G-HT7LE1B2VB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCDmzgSd7bRnfGiv3VqDblO03pFYotL4XU',
    appId: '1:1059902399419:android:0883b4ed5eacc12b031a9e',
    messagingSenderId: '1059902399419',
    projectId: 'dishh-c672c',
    storageBucket: 'dishh-c672c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBKgMtM6_jl_4bz4yuMOHho3CkguXSystM',
    appId: '1:1059902399419:ios:c3f1d814b74f28d4031a9e',
    messagingSenderId: '1059902399419',
    projectId: 'dishh-c672c',
    storageBucket: 'dishh-c672c.appspot.com',
    iosBundleId: 'com.example.dishh',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBKgMtM6_jl_4bz4yuMOHho3CkguXSystM',
    appId: '1:1059902399419:ios:c3f1d814b74f28d4031a9e',
    messagingSenderId: '1059902399419',
    projectId: 'dishh-c672c',
    storageBucket: 'dishh-c672c.appspot.com',
    iosBundleId: 'com.example.dishh',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA9VLC5pwOT-qa5Bnbtzt-GddH_kYWHRa4',
    appId: '1:1059902399419:web:47ef8314f9077bc1031a9e',
    messagingSenderId: '1059902399419',
    projectId: 'dishh-c672c',
    authDomain: 'dishh-c672c.firebaseapp.com',
    storageBucket: 'dishh-c672c.appspot.com',
    measurementId: 'G-4X0W5H7RBY',
  );

}